name: zlak-on.net
favicon: null
layout_spectrum: 0.99654
typography_spectrum: 0.2501
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3466802288312465
  lightness: 0.8924421882256866
  saturation: 0.8029228365048766
  rhythmicContrast: 0.8476968056056648
purpose: []
